/**
 * Help Content Model — the single source of truth for explainable UI.
 *
 * This catalog powers two things the owner asked for:
 *   1. Contextual "What is this?" help — click any explainable screen, section
 *      or control and read what it is *for* (not just what it is called).
 *   2. The canonical key list that guided tutorials, the help popover (Dev 2),
 *      and the anchor-instrumentation pass (Dev 5) all build on, so nobody has
 *      to guess key names.
 *
 * Design rules (kept deliberately simple):
 *   - `key` mirrors the `data-tour` attribute and follows `area.element`
 *     (lowercase area, camelCase element). The live `data-tour` attribute in
 *     the DOM remains the runtime source of truth; this file is the catalog
 *     of what *should* exist plus its plain-language meaning.
 *   - `help` explains the business value — what a real operator uses it for —
 *     never filler like "demo placeholder" or "button that opens a modal".
 *   - `requiredForV1` marks the keys that make up the V1 explainability
 *     coverage target (every screen, every guided-tutorial target, and the
 *     primary shell controls). Lower-priority sections/controls are seeded now
 *     but not required, so Developer 5 has a clear "must instrument" list
 *     without the checker hard-failing on keys that aren't placed yet.
 *
 * Apostrophes in prose use the typographic form (U+2019) on purpose: the
 * dependency-free checker parses single-quoted fields, and this keeps long
 * copy from terminating a string early — the same convention flows.ts uses.
 *
 * This module has zero runtime dependencies.
 */

// ─── Types ───────────────────────────────────────────────────────────────────

export type HelpTier = 'screen' | 'section' | 'control';

export type HelpImportance = 'primary' | 'secondary';

/**
 * Every functional area that can own explainable elements. Sourced here so the
 * compatibility registry (src/tutorials/registry.ts) can re-use it and the two
 * never drift apart again.
 */
export const HELP_AREAS = [
  'topbar',
  'sidebar',
  'dashboard',
  'contacts',
  'conversations',
  'opportunities',
  'calendars',
  'tasks',
  'automations',
  'marketing',
  'reputation',
  'phone',
  'payments',
  'documents',
  'integrations',
  'productivity',
  'media',
  'sites',
  'reporting',
  'settings',
  'guides',
] as const;

export type HelpArea = (typeof HELP_AREAS)[number];

export interface HelpEntry {
  /** Canonical `data-tour` key, e.g. `contacts.addButton`. Unique. */
  key: string;
  /** Functional area this element belongs to. */
  area: HelpArea;
  /** Granularity of the element: a whole screen, a section, or a single control. */
  tier: HelpTier;
  /** Short human label with no trailing punctuation, e.g. "Add Contact button". */
  label: string;
  /** Plain-language, business-value explanation shown in "What is this?". */
  help: string;
  /** Relative prominence for contextual-help affordances. Defaults to secondary. */
  importance?: HelpImportance;
  /** Runtime tutorial flow id (from flows.ts) that walks through this element. */
  tutorialId?: string;
  /** Part of the V1 explainability coverage target (screens, tutorial targets, primary shell). */
  requiredForV1?: boolean;
}

// ─── Catalog ───────────────────────────────────────────────────────────────
//
// Keys below are real `data-tour` values rendered in the app today unless
// flagged in a comment as planned (an anchor Developer 5 still needs to place).
// `tutorialId` values reference the runtime flow ids in src/tutorials/flows.ts.

export const HELP_CONTENT: HelpEntry[] = [
  // ── Top bar (global shell) ────────────────────────────────────────────────
  {
    key: 'topbar',
    area: 'topbar',
    tier: 'section',
    label: 'Top bar',
    help: 'The command strip that stays with you on every screen. Search, notifications, quick-add, the demo controls and your account menu all live here so the tools you reach for constantly are always one click away.',
    importance: 'secondary',
    requiredForV1: true,
  },
  {
    key: 'topbar.accountSwitcher',
    area: 'topbar',
    tier: 'control',
    label: 'Sub-account switcher',
    help: 'Jump between the client sub-accounts you manage. Agencies run many businesses from one login, and switching here re-scopes every screen — contacts, pipelines, calendars — to the account you pick.',
    importance: 'secondary',
    requiredForV1: true,
  },
  {
    key: 'topbar.search',
    area: 'topbar',
    tier: 'control',
    label: 'Global search',
    help: 'Find any contact, conversation, opportunity or appointment without hunting through menus. Start typing a name or number and jump straight to the record, which keeps you fast when a client is on the line.',
    importance: 'primary',
    requiredForV1: true,
  },
  {
    key: 'topbar.notifications',
    area: 'topbar',
    tier: 'control',
    label: 'Notification bell',
    help: 'Your running feed of what needs attention — new messages, missed calls, won deals and booked appointments. Checking it first thing makes sure no hot lead waits while you are busy elsewhere.',
    importance: 'secondary',
    requiredForV1: true,
  },
  {
    key: 'topbar.quickAdd',
    area: 'topbar',
    tier: 'control',
    label: 'Quick-add menu',
    help: 'Create a contact, task, appointment or opportunity from anywhere in the app. Capture the detail the moment it comes up instead of navigating away and losing your place.',
    importance: 'secondary',
    requiredForV1: false,
  },
  {
    key: 'topbar.modeToggle',
    area: 'topbar',
    tier: 'control',
    label: 'Demo / Tutorial mode toggle',
    help: 'Switch between exploring the workspace freely and running a guided walkthrough. Tutorial mode spotlights each step so you learn a workflow by doing it, then hand off to demo mode to try it yourself.',
    importance: 'secondary',
    requiredForV1: true,
  },
  {
    key: 'topbar.resetDemo',
    area: 'topbar',
    tier: 'control',
    label: 'Reset Demo button',
    help: 'Restore the sample data to its original state in one click. Handy before a fresh demo or after experimenting, so the workspace always looks tidy for the next person who sees it.',
    importance: 'secondary',
    requiredForV1: true,
  },
  {
    key: 'topbar.guides',
    area: 'topbar',
    tier: 'control',
    label: 'Help & guides button',
    help: 'Open the guides and help center to launch a tutorial or learn a screen. This is the front door to everything explainable, so it is where you point a new user who feels stuck.',
    importance: 'secondary',
    requiredForV1: true,
  },
  {
    key: 'topbar.dialer',
    area: 'topbar',
    tier: 'control',
    label: 'Phone dialer button',
    help: 'Open the click-to-call dialer to place a call without leaving the page you are on. Calling a lead back quickly is one of the highest-impact things you can do, and this keeps it a single click away.',
    importance: 'secondary',
    requiredForV1: false,
  },
  {
    key: 'topbar.userMenu',
    area: 'topbar',
    tier: 'control',
    label: 'Account menu',
    help: 'Reach your profile, preferences and sign-out from here. It is the personal corner of the shell where account-level settings live, separate from the business settings in the sidebar.',
    importance: 'secondary',
    requiredForV1: false,
  },
  {
    key: 'topbar.mobileNav',
    area: 'topbar',
    tier: 'control',
    label: 'Mobile navigation button',
    help: 'Open the navigation menu on small screens where the sidebar is collapsed. It keeps every module reachable when you are working from a phone or a narrow window.',
    importance: 'secondary',
    requiredForV1: false,
  },

  // ── Sidebar (global navigation) ───────────────────────────────────────────
  {
    key: 'sidebar.nav',
    area: 'sidebar',
    tier: 'section',
    label: 'Main navigation',
    help: 'The map of the whole platform. Each item is a module — Conversations, Contacts, Opportunities and the rest — and this is how you move between the jobs you do in a day.',
    importance: 'primary',
    requiredForV1: true,
  },
  {
    key: 'nav.collapseToggle',
    area: 'sidebar',
    tier: 'control',
    label: 'Collapse sidebar toggle',
    help: 'Shrink the navigation to icons to reclaim screen width for the work area, or expand it back to labels. Useful on wide dashboards and pipelines where every pixel of room helps.',
    importance: 'secondary',
    requiredForV1: false,
  },

  // ── Dashboard ─────────────────────────────────────────────────────────────
  {
    key: 'dashboard.page',
    area: 'dashboard',
    tier: 'screen',
    label: 'Dashboard',
    help: 'Your morning briefing: pipeline value, new leads, unread conversations, upcoming appointments and revenue at a glance. Start here to see what changed overnight and where your attention is needed today.',
    importance: 'primary',
    requiredForV1: true,
  },
  {
    key: 'dashboard.onboardingChecklist',
    area: 'dashboard',
    tier: 'section',
    label: 'Onboarding checklist',
    help: 'A short list of first steps that get a new account producing results — connect a channel, add a contact, build a pipeline. Working through it is the fastest path from empty workspace to live business.',
    importance: 'secondary',
    requiredForV1: false,
  },

  // ── Contacts ──────────────────────────────────────────────────────────────
  {
    key: 'contacts.page',
    area: 'contacts',
    tier: 'screen',
    label: 'Contacts',
    help: 'The CRM home for every lead and client. Each row is one person with their full history, so conversations, appointments, opportunities and payments all stay connected to a single record.',
    importance: 'primary',
    tutorialId: 'add-contact',
    requiredForV1: true,
  },
  {
    key: 'contacts.addButton',
    area: 'contacts',
    tier: 'control',
    label: 'Add Contact button',
    help: 'Use this to add a new lead or customer into your CRM so future conversations, appointments and opportunities stay connected to one record. Capturing a contact early is what lets automations and follow-up work later.',
    importance: 'primary',
    tutorialId: 'add-contact',
    requiredForV1: true,
  },
  {
    key: 'contacts.addModal',
    area: 'contacts',
    tier: 'section',
    label: 'Add Contact form',
    help: 'Where you enter a new person’s name, email, phone and tags. Filling in good detail and a tag up front makes the contact easy to find, segment and automate against down the line.',
    importance: 'secondary',
    tutorialId: 'add-contact',
    requiredForV1: true,
  },
  {
    key: 'contacts.addSubmit',
    area: 'contacts',
    tier: 'control',
    label: 'Save Contact button',
    help: 'Saves the new contact and drops it straight to the top of your list. From that moment the record can receive messages, be added to a pipeline and trigger any matching automation.',
    importance: 'secondary',
    tutorialId: 'add-contact',
    requiredForV1: true,
  },
  {
    key: 'contacts.table',
    area: 'contacts',
    tier: 'section',
    label: 'Contacts table',
    help: 'The sortable list of everyone in your CRM. Scan it to spot who is new, who has gone quiet, and who is worth a call today — then click any row to open the full record.',
    importance: 'secondary',
    requiredForV1: false,
  },
  {
    key: 'contacts.row',
    area: 'contacts',
    tier: 'control',
    label: 'Contact row',
    help: 'A single person in the list. Click it to open their detail view with the complete timeline, so you walk into the next conversation already knowing the history.',
    importance: 'secondary',
    requiredForV1: false,
  },
  {
    key: 'contacts.smartLists',
    area: 'contacts',
    tier: 'section',
    label: 'Smart lists',
    help: 'Saved, auto-updating segments such as "new this week" or "tagged hot". They let you work a focused group of contacts repeatedly without rebuilding the same filter every time.',
    importance: 'secondary',
    requiredForV1: false,
  },
  {
    key: 'contacts.advancedFiltersButton',
    area: 'contacts',
    tier: 'control',
    label: 'Advanced filters',
    help: 'Narrow the list by tag, owner, source or activity to answer a specific question — like which leads from last month never got a reply. The result can be saved as a smart list to reuse.',
    importance: 'secondary',
    requiredForV1: false,
  },
  {
    key: 'contacts.bulkBar',
    area: 'contacts',
    tier: 'section',
    label: 'Bulk actions bar',
    help: 'Appears when you select multiple contacts so you can tag, reassign or remove them in one move. It turns tidying or routing a whole segment into a few seconds of work.',
    importance: 'secondary',
    requiredForV1: false,
  },
  {
    key: 'contacts.detail',
    area: 'contacts',
    tier: 'screen',
    label: 'Contact detail',
    help: 'The full picture of one person — contact info, tags, owner, and a timeline of every message, call, appointment and deal. This is where you prepare for and log each interaction.',
    importance: 'secondary',
    requiredForV1: false,
  },
  {
    key: 'contacts.detailTabs',
    area: 'contacts',
    tier: 'section',
    label: 'Contact detail tabs',
    help: 'Switch between a contact’s conversations, appointments, opportunities and notes. Each tab is a different slice of the relationship, kept in one place so nothing about the client is scattered.',
    importance: 'secondary',
    requiredForV1: false,
  },

  // ── Conversations ─────────────────────────────────────────────────────────
  {
    key: 'conversations.page',
    area: 'conversations',
    tier: 'screen',
    label: 'Conversations',
    help: 'One unified inbox for SMS, email, web chat and social. Talking to every lead from a single place means faster replies and a complete thread, no matter which channel they reached out on.',
    importance: 'primary',
    requiredForV1: true,
  },
  {
    key: 'conversations.list',
    area: 'conversations',
    tier: 'section',
    label: 'Conversation list',
    help: 'Every thread across all channels, with unread ones highlighted so the people waiting on you rise to the top. Working it top-down is how you keep response times short.',
    importance: 'primary',
    tutorialId: 'reply-conversation',
    requiredForV1: true,
  },
  {
    key: 'conversations.threadItem',
    area: 'conversations',
    tier: 'control',
    label: 'Conversation thread item',
    help: 'A single conversation in the list. Click it to read the full back-and-forth in the center pane before you reply, so your answer always has context.',
    importance: 'secondary',
    tutorialId: 'reply-conversation',
    requiredForV1: true,
  },
  {
    key: 'conversations.composer',
    area: 'conversations',
    tier: 'control',
    label: 'Message composer',
    help: 'Where you write your reply, switch channels and drop in saved snippets. Keeping the composer right next to the history means you respond in the same window you read in.',
    importance: 'secondary',
    tutorialId: 'reply-conversation',
    requiredForV1: true,
  },
  {
    key: 'conversations.sendButton',
    area: 'conversations',
    tier: 'control',
    label: 'Send button',
    help: 'Sends your reply and posts it instantly to the thread (demo only — nothing actually leaves). A prompt reply here is often the difference between booking the lead and losing them.',
    importance: 'secondary',
    tutorialId: 'reply-conversation',
    requiredForV1: true,
  },
  {
    key: 'conversations.inbox',
    area: 'conversations',
    tier: 'section',
    label: 'Inbox pane',
    help: 'The left column that holds your filters and the conversation list. It is the navigator for the inbox — pick a view here and the thread opens beside it.',
    importance: 'secondary',
    requiredForV1: false,
  },
  {
    key: 'conversations.filters',
    area: 'conversations',
    tier: 'control',
    label: 'Conversation filters',
    help: 'Narrow the inbox to unread, a single channel, or just your own conversations. Filtering keeps a busy inbox focused so you work the messages that matter first.',
    importance: 'secondary',
    requiredForV1: false,
  },
  {
    key: 'conversations.thread',
    area: 'conversations',
    tier: 'section',
    label: 'Message thread',
    help: 'The center pane that shows the full message history for the selected conversation. Reading it before replying keeps the exchange coherent and personal.',
    importance: 'secondary',
    requiredForV1: false,
  },
  {
    key: 'conversations.contactContext',
    area: 'conversations',
    tier: 'section',
    label: 'Contact context panel',
    help: 'The right-hand panel with the contact’s details, tags and recent activity while you chat. It puts who you are talking to next to what you are saying, so replies stay relevant.',
    importance: 'secondary',
    requiredForV1: false,
  },

  // ── Opportunities ─────────────────────────────────────────────────────────
  {
    key: 'opportunities.page',
    area: 'opportunities',
    tier: 'screen',
    label: 'Opportunities',
    help: 'Your sales pipeline — every active deal and where it stands. Seeing the whole funnel in one view tells you what is likely to close and what needs a nudge to keep revenue moving.',
    importance: 'primary',
    requiredForV1: true,
  },
  {
    key: 'opportunities.board',
    area: 'opportunities',
    tier: 'section',
    label: 'Pipeline board',
    help: 'The kanban view of your pipeline, one column per stage with deal counts and totals in each header. It makes the health of your funnel obvious at a glance.',
    importance: 'primary',
    tutorialId: 'move-pipeline',
    requiredForV1: true,
  },
  {
    key: 'opportunities.card',
    area: 'opportunities',
    tier: 'control',
    label: 'Opportunity card',
    help: 'A single deal showing its name, value and contact. Drag it between columns as the deal progresses, or click it to see and update the full detail.',
    importance: 'secondary',
    tutorialId: 'move-pipeline',
    requiredForV1: true,
  },
  {
    key: 'opportunities.stageColumn',
    area: 'opportunities',
    tier: 'section',
    label: 'Pipeline stage column',
    help: 'One stage of your sales process. Drop a card here to move the deal forward; the column totals recalculate live so your forecast always reflects reality.',
    importance: 'secondary',
    tutorialId: 'move-pipeline',
    requiredForV1: true,
  },
  {
    key: 'opportunities.pipelineSelector',
    area: 'opportunities',
    tier: 'control',
    label: 'Pipeline selector',
    help: 'Switch between different sales processes — for example new sales versus renewals. Each pipeline has its own stages, so this keeps unrelated deals from crowding the same board.',
    importance: 'secondary',
    requiredForV1: false,
  },
  {
    key: 'opportunities.viewToggle',
    area: 'opportunities',
    tier: 'control',
    label: 'Board / list toggle',
    help: 'Flip between the visual board and a sortable list of the same deals. The board is best for moving work along; the list is best for filtering and bulk edits.',
    importance: 'secondary',
    requiredForV1: false,
  },
  {
    key: 'opportunities.list',
    area: 'opportunities',
    tier: 'section',
    label: 'Opportunities list',
    help: 'A table view of every deal you can sort and filter. Use it when you want to slice the pipeline by owner, value or stage rather than drag cards around.',
    importance: 'secondary',
    requiredForV1: false,
  },
  {
    key: 'opportunities.add',
    area: 'opportunities',
    tier: 'control',
    label: 'Add Opportunity button',
    help: 'Create a new deal and attach it to a contact and stage. Logging an opportunity is how a promising conversation becomes something you can track, forecast and follow up on.',
    importance: 'secondary',
    requiredForV1: false,
  },

  // ── Calendars ─────────────────────────────────────────────────────────────
  {
    key: 'calendars.page',
    area: 'calendars',
    tier: 'screen',
    label: 'Calendars',
    help: 'Your booking and scheduling hub across Month, Week, Day and Agenda views. A clear calendar means appointments do not collide and clients always know when they will be seen.',
    importance: 'primary',
    tutorialId: 'book-appointment',
    requiredForV1: true,
  },
  {
    key: 'calendars.bookButton',
    area: 'calendars',
    tier: 'control',
    label: 'Book Appointment button',
    help: 'Open the booking form to schedule a contact onto a calendar. Booking inside the platform keeps the appointment tied to the client’s record and any reminders that follow.',
    importance: 'primary',
    tutorialId: 'book-appointment',
    requiredForV1: true,
  },
  {
    key: 'calendars.bookModal',
    area: 'calendars',
    tier: 'section',
    label: 'Booking form',
    help: 'Pick the calendar, the contact and a time slot for the appointment. Choosing the right calendar matters because each one can carry its own availability and notifications.',
    importance: 'secondary',
    tutorialId: 'book-appointment',
    requiredForV1: true,
  },
  {
    key: 'calendars.bookSubmit',
    area: 'calendars',
    tier: 'control',
    label: 'Confirm booking button',
    help: 'Confirms the appointment and places it on the grid right away. The contact and time are now locked in, ready for reminders and any follow-up automation.',
    importance: 'secondary',
    tutorialId: 'book-appointment',
    requiredForV1: true,
  },
  {
    key: 'calendars.selector',
    area: 'calendars',
    tier: 'control',
    label: 'Calendar selector',
    help: 'Choose which calendars to show — for example per staff member or service. Toggling them keeps a shared schedule readable when several people are booking at once.',
    importance: 'secondary',
    requiredForV1: false,
  },
  {
    key: 'calendars.viewToggle',
    area: 'calendars',
    tier: 'control',
    label: 'Calendar view toggle',
    help: 'Switch between Month, Week, Day and Agenda. Month is best for spotting open days, Day and Agenda for working through a packed schedule hour by hour.',
    importance: 'secondary',
    requiredForV1: false,
  },
  {
    key: 'calendars.monthGrid',
    area: 'calendars',
    tier: 'section',
    label: 'Month grid',
    help: 'The month-at-a-glance grid where each day shows its appointments. Click an empty slot to start a booking on that date without opening the form first.',
    importance: 'secondary',
    requiredForV1: false,
  },
  {
    key: 'calendars.agenda',
    area: 'calendars',
    tier: 'section',
    label: 'Agenda view',
    help: 'A chronological list of upcoming appointments. It is the cleanest way to see exactly what your day holds and in what order.',
    importance: 'secondary',
    requiredForV1: false,
  },

  // ── Tasks ─────────────────────────────────────────────────────────────────
  {
    key: 'tasks.page',
    area: 'tasks',
    tier: 'screen',
    label: 'Tasks',
    help: 'Your to-do list tied to contacts and deals. Tracking follow-ups as tasks is how commitments to clients actually get done instead of living in your head.',
    importance: 'secondary',
    requiredForV1: true,
  },
  {
    key: 'tasks.addButton',
    area: 'tasks',
    tier: 'control',
    label: 'Add Task button',
    help: 'Create a task with a due date and, optionally, a linked contact. Writing down the next step the moment you agree to it keeps promises from slipping.',
    importance: 'secondary',
    requiredForV1: false,
  },
  {
    key: 'tasks.list',
    area: 'tasks',
    tier: 'section',
    label: 'Task list',
    help: 'All your open and completed tasks in one place. Clearing it daily is a simple discipline that keeps follow-up reliable across every client.',
    importance: 'secondary',
    requiredForV1: false,
  },
  {
    key: 'tasks.row',
    area: 'tasks',
    tier: 'control',
    label: 'Task row',
    help: 'A single task showing what is due and when. Click through to the linked contact so you can act on it with the full history in front of you.',
    importance: 'secondary',
    requiredForV1: false,
  },
  {
    key: 'tasks.toggle',
    area: 'tasks',
    tier: 'control',
    label: 'Complete task toggle',
    help: 'Mark a task done. Ticking things off keeps your list honest and gives you a record of the follow-ups you have actually completed.',
    importance: 'secondary',
    requiredForV1: false,
  },

  // ── Automations ───────────────────────────────────────────────────────────
  {
    key: 'automations.page',
    area: 'automations',
    tier: 'screen',
    label: 'Automations',
    help: 'Where you build workflows that run on their own — a missed call texts back, a new lead gets nurtured, a won deal triggers an invoice. This is how follow-up happens 24/7 without you.',
    importance: 'primary',
    requiredForV1: true,
  },
  {
    key: 'automations.list',
    area: 'automations',
    tier: 'section',
    label: 'Workflow list',
    help: 'Every workflow you have, with its trigger and whether it is live. Scanning it tells you what is currently working for you automatically and what is still in draft.',
    importance: 'primary',
    tutorialId: 'create-workflow',
    requiredForV1: true,
  },
  {
    key: 'automations.addButton',
    area: 'automations',
    tier: 'control',
    label: 'Create Workflow button',
    help: 'Start a new workflow from a blank canvas or a ready-made template. Automating a repetitive follow-up once here saves you from doing it by hand forever after.',
    importance: 'primary',
    tutorialId: 'create-workflow',
    requiredForV1: true,
  },
  {
    key: 'automations.row',
    area: 'automations',
    tier: 'control',
    label: 'Workflow row',
    help: 'A single workflow in the list. Click it to open the visual builder, where a trigger connects to action steps like Send SMS or Send Email.',
    importance: 'secondary',
    tutorialId: 'create-workflow',
    requiredForV1: true,
  },
  {
    key: 'automations.publishToggle',
    area: 'automations',
    tier: 'control',
    label: 'Publish toggle',
    help: 'Flip a workflow between Draft and Published. Published workflows go live immediately and start acting on their trigger, so this is the switch that turns an idea into automation.',
    importance: 'secondary',
    tutorialId: 'create-workflow',
    requiredForV1: true,
  },
  {
    key: 'automations.canvas',
    area: 'automations',
    tier: 'section',
    label: 'Workflow builder canvas',
    help: 'The visual space where a trigger flows into action steps. Building left to right here lets you see the whole follow-up sequence a contact will experience.',
    importance: 'secondary',
    requiredForV1: false,
  },
  {
    key: 'automations.triggerNode',
    area: 'automations',
    tier: 'control',
    label: 'Trigger step',
    help: 'The event that starts a workflow — a new lead, a missed call, a form submission. Choosing the right trigger is what makes the automation fire at exactly the right moment.',
    importance: 'secondary',
    requiredForV1: false,
  },
  {
    key: 'automations.actionNode',
    area: 'automations',
    tier: 'control',
    label: 'Action step',
    help: 'Something the workflow does after the trigger, such as send a message, add a tag or wait. Chaining actions builds the automated follow-up your leads receive.',
    importance: 'secondary',
    requiredForV1: false,
  },
  {
    key: 'automations.addNodeButton',
    area: 'automations',
    tier: 'control',
    label: 'Add step button',
    help: 'Insert another action into the workflow. Each step you add extends the sequence — for example following an SMS with a wait and then an email.',
    importance: 'secondary',
    requiredForV1: false,
  },
  {
    key: 'automations.nodeDrawer',
    area: 'automations',
    tier: 'section',
    label: 'Step settings drawer',
    help: 'Where you configure the selected step — the message text, the tag, the delay. Getting these details right is what makes the automation feel personal rather than robotic.',
    importance: 'secondary',
    requiredForV1: false,
  },

  // ── Marketing ─────────────────────────────────────────────────────────────
  {
    key: 'marketing.page',
    area: 'marketing',
    tier: 'screen',
    label: 'Marketing',
    help: 'Plan and review your email and SMS campaigns. Sending broadcasts to the right segment is how you stay top-of-mind and bring quiet contacts back into conversations.',
    importance: 'primary',
    requiredForV1: true,
  },
  {
    key: 'marketing.campaignList',
    area: 'marketing',
    tier: 'section',
    label: 'Campaign list',
    help: 'All your campaigns with their status — Sent, Scheduled or Draft — and headline metrics. It is the quick read on what has gone out and what is queued up.',
    importance: 'primary',
    tutorialId: 'view-campaign-performance',
    requiredForV1: true,
  },
  {
    key: 'marketing.summary',
    area: 'marketing',
    tier: 'section',
    label: 'Campaign summary metrics',
    help: 'Top-line numbers that roll up audience size, delivery, opens and clicks across campaigns. These tell you what is resonating so you can do more of what works.',
    importance: 'secondary',
    tutorialId: 'view-campaign-performance',
    requiredForV1: true,
  },
  {
    key: 'marketing.campaignRow',
    area: 'marketing',
    tier: 'control',
    label: 'Campaign row',
    help: 'A single campaign in the list. Click a sent one to drill into its open rate, click rate and delivery breakdown and judge whether the message landed.',
    importance: 'secondary',
    tutorialId: 'view-campaign-performance',
    requiredForV1: true,
  },
  {
    key: 'marketing.tabs',
    area: 'marketing',
    tier: 'control',
    label: 'Email / SMS tabs',
    help: 'Switch between your email and SMS campaigns. Each channel suits different messages — email for detail, SMS for urgency — so this keeps them organized separately.',
    importance: 'secondary',
    requiredForV1: false,
  },
  {
    key: 'marketing.newCampaign',
    area: 'marketing',
    tier: 'control',
    label: 'New Campaign button',
    help: 'Start building a new broadcast to a chosen audience. A well-targeted campaign re-engages leads who have gone cold and fills the top of your pipeline.',
    importance: 'secondary',
    requiredForV1: false,
  },
  {
    key: 'marketing.campaignDetail',
    area: 'marketing',
    tier: 'section',
    label: 'Campaign detail',
    help: 'The full performance view for one campaign — delivery, opens, clicks and the audience it reached. Use it to learn which subject lines and offers actually drive replies.',
    importance: 'secondary',
    requiredForV1: false,
  },

  // ── Reputation ────────────────────────────────────────────────────────────
  {
    key: 'reputation.page',
    area: 'reputation',
    tier: 'screen',
    label: 'Reputation',
    help: 'Monitor and grow your reviews across Google and Facebook. A steady stream of fresh 5-star reviews builds trust and quietly brings in new prospects on its own.',
    importance: 'primary',
    requiredForV1: true,
  },
  {
    key: 'reputation.summary',
    area: 'reputation',
    tier: 'section',
    label: 'Reputation summary',
    help: 'Your average rating and review volume at a glance. Watching these trend up is a simple gauge of how your reputation work is paying off.',
    importance: 'primary',
    tutorialId: 'send-review-request',
    requiredForV1: true,
  },
  {
    key: 'reputation.requestButton',
    area: 'reputation',
    tier: 'control',
    label: 'Send Review Request button',
    help: 'Ask a happy client for a review by SMS or email. Requesting at the right moment — just after a great experience — is the most reliable way to earn more 5-star reviews.',
    importance: 'primary',
    tutorialId: 'send-review-request',
    requiredForV1: true,
  },
  {
    key: 'reputation.channelChoice',
    area: 'reputation',
    tier: 'control',
    label: 'Review request channel choice',
    help: 'Pick whether the request goes by SMS or email and choose the contact. Matching the channel to how the client normally hears from you lifts the response rate.',
    importance: 'secondary',
    tutorialId: 'send-review-request',
    requiredForV1: true,
  },
  {
    key: 'reputation.requestSubmit',
    area: 'reputation',
    tier: 'control',
    label: 'Send request button',
    help: 'Sends the pre-written review request (demo only) and confirms with a toast. The client receives a one-tap link, which removes the friction that usually stops people from leaving a review.',
    importance: 'secondary',
    tutorialId: 'send-review-request',
    requiredForV1: true,
  },
  {
    key: 'reputation.reviewList',
    area: 'reputation',
    tier: 'section',
    label: 'Reviews list',
    help: 'Every review you have received across connected sites. Reading and replying to them shows prospective customers that you are attentive and engaged.',
    importance: 'secondary',
    requiredForV1: false,
  },
  {
    key: 'reputation.reviewRow',
    area: 'reputation',
    tier: 'control',
    label: 'Review row',
    help: 'A single review. Open it to read the full text and reply — responding to both praise and criticism is part of a healthy public reputation.',
    importance: 'secondary',
    requiredForV1: false,
  },
  {
    key: 'reputation.breakdown',
    area: 'reputation',
    tier: 'section',
    label: 'Rating breakdown',
    help: 'How your reviews split across star ratings and sources. It highlights where your reputation is strong and which platform needs more attention.',
    importance: 'secondary',
    requiredForV1: false,
  },

  // ── Phone ─────────────────────────────────────────────────────────────────
  {
    key: 'phone.page',
    area: 'phone',
    tier: 'screen',
    label: 'Phone',
    help: 'Your calling hub — call history, voicemails and the dialer. Keeping calls inside the platform means every conversation is logged against the contact automatically.',
    importance: 'primary',
    requiredForV1: true,
  },
  {
    key: 'phone.callLog',
    area: 'phone',
    tier: 'section',
    label: 'Call log',
    help: 'Every inbound, outbound and missed call with duration and caller details. It is the record that makes sure no call — especially a missed one — goes unnoticed.',
    importance: 'primary',
    tutorialId: 'check-missed-calls',
    requiredForV1: true,
  },
  {
    key: 'phone.filters',
    area: 'phone',
    tier: 'control',
    label: 'Call log filters',
    help: 'Narrow the log to just missed calls so nothing slips by. Following up on missed calls fast is one of the quickest ways to win business you would otherwise lose.',
    importance: 'secondary',
    tutorialId: 'check-missed-calls',
    requiredForV1: true,
  },
  {
    key: 'phone.callRow',
    area: 'phone',
    tier: 'control',
    label: 'Call log row',
    help: 'A single call. Open it to see the caller’s info and any voicemail transcript, so you can call back already knowing what they wanted.',
    importance: 'secondary',
    tutorialId: 'check-missed-calls',
    requiredForV1: true,
  },
  {
    key: 'phone.dialerButton',
    area: 'phone',
    tier: 'control',
    label: 'Open dialer button',
    help: 'Bring up the keypad to place a call. Quick outbound dialing right from this screen keeps you working the phone instead of switching apps.',
    importance: 'secondary',
    requiredForV1: false,
  },
  {
    key: 'phone.dialer',
    area: 'phone',
    tier: 'section',
    label: 'Dialer',
    help: 'The click-to-call keypad. Calls placed here are logged to the contact automatically, so your history stays complete without any manual note-taking.',
    importance: 'secondary',
    requiredForV1: false,
  },
  {
    key: 'phone.callDetail',
    area: 'phone',
    tier: 'section',
    label: 'Call detail',
    help: 'The full record of one call, including recording or voicemail where available. It gives you the context to return the call well rather than blind.',
    importance: 'secondary',
    requiredForV1: false,
  },
  {
    key: 'phone.summary',
    area: 'phone',
    tier: 'section',
    label: 'Call summary',
    help: 'A roll-up of call volume and missed-call counts. Watching it shows whether you are keeping up with inbound demand or leaving callers hanging.',
    importance: 'secondary',
    requiredForV1: false,
  },

  // ── Payments ──────────────────────────────────────────────────────────────
  {
    key: 'payments.page',
    area: 'payments',
    tier: 'screen',
    label: 'Payments',
    help: 'Invoicing, products, transactions and subscriptions in one place. Billing inside the platform gets you paid faster and keeps the money side tied to each client record.',
    importance: 'primary',
    requiredForV1: true,
  },
  {
    key: 'payments.tabs',
    area: 'payments',
    tier: 'control',
    label: 'Payments tabs',
    help: 'Switch between Invoices, Products, Transactions and Subscriptions. Each tab is a different part of getting paid, organized so billing and history never get mixed up.',
    importance: 'secondary',
    tutorialId: 'create-invoice',
    requiredForV1: true,
  },
  {
    key: 'payments.createInvoice',
    area: 'payments',
    tier: 'control',
    label: 'New Invoice button',
    help: 'Build an invoice from your product catalog and send it to a client. A clear, fast invoice removes the awkward back-and-forth and shortens the time until you are paid.',
    importance: 'primary',
    tutorialId: 'create-invoice',
    requiredForV1: true,
  },
  {
    key: 'payments.invoiceModal',
    area: 'payments',
    tier: 'section',
    label: 'Invoice builder',
    help: 'Choose the contact to bill, add line items, and the subtotal and tax total automatically. Accurate line items here are what make the invoice look professional and trustworthy.',
    importance: 'secondary',
    tutorialId: 'create-invoice',
    requiredForV1: true,
  },
  {
    key: 'payments.invoiceSubmit',
    area: 'payments',
    tier: 'control',
    label: 'Send invoice button',
    help: 'Sends the invoice and flips its status to Sent (demo only). The client gets a payable document, and the transaction stays linked to their record for your books.',
    importance: 'secondary',
    tutorialId: 'create-invoice',
    requiredForV1: true,
  },
  {
    key: 'payments.invoiceList',
    area: 'payments',
    tier: 'section',
    label: 'Invoice list',
    help: 'All your invoices with their status — Draft, Sent or Paid. Scanning it tells you at a glance what is outstanding and who needs a gentle payment reminder.',
    importance: 'secondary',
    requiredForV1: false,
  },
  {
    key: 'payments.invoiceDetail',
    area: 'payments',
    tier: 'section',
    label: 'Invoice detail',
    help: 'The full view of one invoice — line items, totals and payment status. It is where you confirm what was billed and chase anything still unpaid.',
    importance: 'secondary',
    requiredForV1: false,
  },
  {
    key: 'payments.summary',
    area: 'payments',
    tier: 'section',
    label: 'Payments summary',
    help: 'Headline revenue and outstanding-balance figures. Watching them gives you a quick pulse on cash flow without opening every invoice.',
    importance: 'secondary',
    requiredForV1: false,
  },

  // ── Documents (proposals / contracts) ───────────────────────────────────────
  {
    key: 'payments.documentList',
    area: 'documents',
    tier: 'section',
    label: 'Documents list',
    help: 'Your proposals, estimates and contracts. Sending and tracking these in the platform keeps the paperwork that closes a deal attached to the client and the invoice that follows.',
    importance: 'secondary',
    requiredForV1: false,
  },
  {
    key: 'payments.documentEditor',
    area: 'documents',
    tier: 'section',
    label: 'Document editor',
    help: 'Where you draft a proposal or contract and add line items. A polished, clear document speeds up the client’s yes and converts straight into an invoice.',
    importance: 'secondary',
    requiredForV1: false,
  },
  {
    // Planned: dedicated Documents screen anchor — Developer 5 to place when the
    // Documents route gets its own top-level container.
    key: 'documents.page',
    area: 'documents',
    tier: 'screen',
    label: 'Documents',
    help: 'A home for proposals, estimates and contracts. Managing them alongside payments means the document that wins the work and the invoice that bills it stay connected to one client.',
    importance: 'secondary',
    requiredForV1: false,
  },

  // ── Integrations ──────────────────────────────────────────────────────────
  {
    key: 'integrations.page',
    area: 'integrations',
    tier: 'screen',
    label: 'Integrations',
    help: 'Connect the outside tools you already use — email, calendars and more. Linking them pulls that activity into the platform so you stop switching tabs to get the full picture.',
    importance: 'primary',
    requiredForV1: true,
  },
  {
    key: 'integrations.cards',
    area: 'integrations',
    tier: 'section',
    label: 'Connected accounts',
    help: 'The grid of services you can link, each with a connect action. This is where you wire up an email or calendar account so its messages and events show up inside the platform.',
    importance: 'primary',
    tutorialId: 'outlook-inbox',
    requiredForV1: true,
  },
  {
    key: 'integrations.connectOutlook',
    area: 'integrations',
    tier: 'control',
    label: 'Connect Outlook button',
    help: 'Run the mock connection flow for an Outlook-style inbox (it succeeds instantly in the demo). Connecting email means you can read and reply without leaving your workspace.',
    importance: 'secondary',
    tutorialId: 'outlook-inbox',
    requiredForV1: true,
  },
  {
    key: 'integrations.outlookInbox',
    area: 'integrations',
    tier: 'section',
    label: 'Connected inbox',
    help: 'Your linked email rendered with folders, a message list and a reading pane. Having email in the same place as your CRM keeps client correspondence in one timeline.',
    importance: 'secondary',
    tutorialId: 'outlook-inbox',
    requiredForV1: true,
  },
  {
    key: 'integrations.oauthModal',
    area: 'integrations',
    tier: 'section',
    label: 'Connection dialog',
    help: 'The authorization step that links an external account (mocked here). In a live account this is where you would grant access so the platform can sync on your behalf.',
    importance: 'secondary',
    requiredForV1: false,
  },
  {
    key: 'integrations.emailRow',
    area: 'integrations',
    tier: 'control',
    label: 'Email row',
    help: 'A single message in the connected inbox. Click it to read the full email in the reading pane and respond in context.',
    importance: 'secondary',
    requiredForV1: false,
  },
  {
    key: 'integrations.readingPane',
    area: 'integrations',
    tier: 'section',
    label: 'Reading pane',
    help: 'Shows the selected email beside the list. Reading and replying side by side keeps you moving through the inbox quickly.',
    importance: 'secondary',
    requiredForV1: false,
  },

  // ── Productivity (projects, tasks, tickets, docs) ───────────────────────────
  {
    key: 'productivity.overview',
    area: 'productivity',
    tier: 'screen',
    label: 'Productivity',
    help: 'A workspace for projects, tickets, tasks and internal docs. Running delivery and support here keeps the work that happens after the sale organized and visible to the team.',
    importance: 'primary',
    requiredForV1: true,
  },
  {
    key: 'productivity.project-list',
    area: 'productivity',
    tier: 'section',
    label: 'Project list',
    help: 'Your active projects and their progress. Tracking client work as projects makes sure delivery stays on schedule and nothing promised gets forgotten.',
    importance: 'secondary',
    requiredForV1: false,
  },
  {
    key: 'productivity.create-task',
    area: 'productivity',
    tier: 'control',
    label: 'Create task button',
    help: 'Add a task to a project or board. Breaking delivery into tracked tasks keeps the team aligned on who is doing what next.',
    importance: 'secondary',
    requiredForV1: false,
  },
  {
    key: 'productivity.create-task-submit',
    area: 'productivity',
    tier: 'control',
    label: 'Save task button',
    help: 'Saves the new task to the board so it shows up for whoever owns it. Logging it here is how delivery work stays out of inboxes and in one shared place.',
    importance: 'secondary',
    requiredForV1: false,
  },
  {
    key: 'productivity.create-ticket',
    area: 'productivity',
    tier: 'control',
    label: 'Create ticket button',
    help: 'Open a support ticket for a client issue. Capturing requests as tickets makes sure they get triaged and answered rather than lost in a thread.',
    importance: 'secondary',
    requiredForV1: false,
  },
  {
    key: 'productivity.create-ticket-submit',
    area: 'productivity',
    tier: 'control',
    label: 'Save ticket button',
    help: 'Saves the support ticket into the queue. From here it can be prioritized and assigned, so customer issues are handled consistently.',
    importance: 'secondary',
    requiredForV1: false,
  },
  {
    key: 'productivity.ticket-stats',
    area: 'productivity',
    tier: 'section',
    label: 'Ticket stats',
    help: 'Open, in-progress and resolved ticket counts. They show whether your team is keeping up with support demand or falling behind.',
    importance: 'secondary',
    requiredForV1: false,
  },
  {
    key: 'productivity.timeline',
    area: 'productivity',
    tier: 'section',
    label: 'Project timeline',
    help: 'A schedule view of project milestones and due dates. Seeing the timeline keeps delivery realistic and helps you spot a slip before it becomes a missed deadline.',
    importance: 'secondary',
    requiredForV1: false,
  },
  {
    key: 'productivity.docs',
    area: 'productivity',
    tier: 'section',
    label: 'Docs',
    help: 'Shared internal documents and notes. Keeping process and project docs next to the work means the team finds answers without asking around.',
    importance: 'secondary',
    requiredForV1: false,
  },
  {
    key: 'productivity.settings',
    area: 'productivity',
    tier: 'section',
    label: 'Productivity settings',
    help: 'Configure boards, statuses and how the productivity workspace behaves. Tuning it to match how your team actually works keeps the tool out of the way.',
    importance: 'secondary',
    requiredForV1: false,
  },

  // ── Media library ───────────────────────────────────────────────────────────
  {
    key: 'media.page',
    area: 'media',
    tier: 'screen',
    label: 'Media library',
    help: 'Central storage for images and files you reuse in messages, campaigns and sites. One library means brand assets stay consistent everywhere they appear.',
    importance: 'secondary',
    requiredForV1: true,
  },
  {
    key: 'media.grid',
    area: 'media',
    tier: 'section',
    label: 'Media grid',
    help: 'Thumbnails of everything in your library. Browse it to find and reuse an asset instead of re-uploading the same file again and again.',
    importance: 'secondary',
    requiredForV1: false,
  },
  {
    key: 'media.uploadButton',
    area: 'media',
    tier: 'control',
    label: 'Upload button',
    help: 'Add a new image or file to the library. Uploading once and reusing keeps your campaigns and pages on-brand with no duplicated effort.',
    importance: 'secondary',
    requiredForV1: false,
  },
  {
    key: 'media.item',
    area: 'media',
    tier: 'control',
    label: 'Media item',
    help: 'A single asset in the library. Open it to preview, copy its link or drop it into a message or page.',
    importance: 'secondary',
    requiredForV1: false,
  },
  {
    key: 'media.filters',
    area: 'media',
    tier: 'control',
    label: 'Media filters',
    help: 'Narrow the library by type or folder. Filtering makes a large asset collection quick to search when you need a specific file.',
    importance: 'secondary',
    requiredForV1: false,
  },

  // ── Sites (funnels / websites / forms / surveys) ────────────────────────────
  {
    key: 'sites.page',
    area: 'sites',
    tier: 'screen',
    label: 'Sites',
    help: 'Build funnels, websites, forms and surveys that capture leads. These pages are the front door that turns a visitor into a contact in your CRM.',
    importance: 'secondary',
    requiredForV1: true,
  },
  {
    key: 'sites.tabs',
    area: 'sites',
    tier: 'control',
    label: 'Sites tabs',
    help: 'Switch between Funnels, Websites and Forms & Surveys. Each builds a different kind of page, organized so your marketing assets stay easy to find.',
    importance: 'secondary',
    requiredForV1: false,
  },
  {
    key: 'sites.grid',
    area: 'sites',
    tier: 'section',
    label: 'Sites grid',
    help: 'Cards for each funnel or site you have built. It is the gallery you work from to edit, preview or launch a page.',
    importance: 'secondary',
    requiredForV1: false,
  },
  {
    key: 'sites.card',
    area: 'sites',
    tier: 'control',
    label: 'Site card',
    help: 'A single funnel or website. Open it to edit pages or check how many visitors it is converting into leads.',
    importance: 'secondary',
    requiredForV1: false,
  },
  {
    key: 'sites.newSite',
    area: 'sites',
    tier: 'control',
    label: 'New site button',
    help: 'Start a new funnel or website. A focused landing page tied to a campaign is one of the most reliable ways to capture new leads.',
    importance: 'secondary',
    requiredForV1: false,
  },
  {
    key: 'sites.formsSurveys',
    area: 'sites',
    tier: 'section',
    label: 'Forms & surveys',
    help: 'Your lead-capture forms and surveys. Every submission becomes a contact, so these are the workhorses that feed your CRM from the web.',
    importance: 'secondary',
    requiredForV1: false,
  },

  // ── Reporting ─────────────────────────────────────────────────────────────
  {
    key: 'reporting.page',
    area: 'reporting',
    tier: 'screen',
    label: 'Reporting',
    help: 'Performance reports across attribution, calls, appointments and revenue. Reporting turns activity into the numbers you use to decide where to spend time and budget.',
    importance: 'primary',
    requiredForV1: true,
  },
  {
    key: 'reporting.tabs',
    area: 'reporting',
    tier: 'control',
    label: 'Report tabs',
    help: 'Switch between report types such as Attribution, Calls and Appointments. Each answers a different business question, kept on its own tab for clarity.',
    importance: 'secondary',
    requiredForV1: false,
  },
  {
    key: 'reporting.kpis',
    area: 'reporting',
    tier: 'section',
    label: 'Report KPIs',
    help: 'The headline numbers for the selected report. They give you the bottom line before you dig into the charts and table beneath.',
    importance: 'secondary',
    requiredForV1: false,
  },
  {
    key: 'reporting.charts',
    area: 'reporting',
    tier: 'section',
    label: 'Report charts',
    help: 'Visual trends for the current report. Charts make it easy to spot what is improving and what is sliding over time.',
    importance: 'secondary',
    requiredForV1: false,
  },
  {
    key: 'reporting.table',
    area: 'reporting',
    tier: 'section',
    label: 'Report data table',
    help: 'The detailed rows behind the charts. Sort and read it when you need the exact figures rather than the high-level shape.',
    importance: 'secondary',
    requiredForV1: false,
  },
  {
    key: 'reporting.dateRange',
    area: 'reporting',
    tier: 'control',
    label: 'Date range picker',
    help: 'Set the period a report covers. Comparing the same report across ranges is how you tell whether a change actually moved the needle.',
    importance: 'secondary',
    requiredForV1: false,
  },
  {
    key: 'reporting.attribution',
    area: 'reporting',
    tier: 'section',
    label: 'Attribution report',
    help: 'Shows which sources and campaigns produced your leads and revenue. Knowing what is working lets you put more budget behind the channels that pay off.',
    importance: 'secondary',
    requiredForV1: false,
  },
  {
    key: 'reporting.aiSummary',
    area: 'reporting',
    tier: 'section',
    label: 'AI summary',
    help: 'A plain-language read of what the report is telling you. It surfaces the takeaway so you do not have to interpret every chart yourself.',
    importance: 'secondary',
    requiredForV1: false,
  },
  {
    key: 'reporting.export',
    area: 'reporting',
    tier: 'control',
    label: 'Export report button',
    help: 'Download the current report (cosmetic in the demo). Exporting is how you share results with a client or pull figures into a deck.',
    importance: 'secondary',
    requiredForV1: false,
  },

  // ── Settings ──────────────────────────────────────────────────────────────
  {
    key: 'settings.page',
    area: 'settings',
    tier: 'screen',
    label: 'Settings',
    help: 'Configure the business behind the workspace — profile, staff, and how features behave. Getting settings right up front shapes how every other module works for your team.',
    importance: 'primary',
    requiredForV1: true,
  },
  {
    key: 'settings.nav',
    area: 'settings',
    tier: 'section',
    label: 'Settings navigation',
    help: 'The menu of settings sections — business profile, team, integrations and more. It is the index you use to jump straight to the area you need to change.',
    importance: 'secondary',
    requiredForV1: false,
  },
  {
    key: 'settings.businessProfile',
    area: 'settings',
    tier: 'section',
    label: 'Business profile',
    help: 'Your company name, contact details and branding. These details appear on invoices, messages and booking pages, so accurate info here keeps every client touchpoint professional.',
    importance: 'secondary',
    requiredForV1: false,
  },
  {
    key: 'settings.staff',
    area: 'settings',
    tier: 'section',
    label: 'Staff & team',
    help: 'Manage the people on your team and what they can access. Adding staff and setting roles is how work gets shared without handing everyone the keys to everything.',
    importance: 'secondary',
    requiredForV1: false,
  },
  {
    key: 'settings.toggles',
    area: 'settings',
    tier: 'control',
    label: 'Feature toggles',
    help: 'Switch optional features and behaviors on or off. Turning off what you do not use keeps the workspace simple and focused for your team.',
    importance: 'secondary',
    requiredForV1: false,
  },
  {
    key: 'settings.configSection',
    area: 'settings',
    tier: 'section',
    label: 'Configuration section',
    help: 'A grouped set of related settings. Working through one section at a time keeps configuration manageable rather than overwhelming.',
    importance: 'secondary',
    requiredForV1: false,
  },

  // ── Guides / Help center ────────────────────────────────────────────────────
  {
    key: 'guides.page',
    area: 'guides',
    tier: 'screen',
    label: 'Guides & help center',
    help: 'The learning hub where you launch guided tutorials and understand any screen. It is the place to send a new user, or to return to whenever a workflow is unfamiliar.',
    importance: 'primary',
    requiredForV1: true,
  },
  {
    key: 'guides.tutorialList',
    area: 'guides',
    tier: 'section',
    label: 'Tutorial list',
    help: 'Every guided walkthrough available, grouped by area. Browsing it is how you find a step-by-step for exactly the task you are trying to learn.',
    importance: 'secondary',
    requiredForV1: true,
  },
  {
    key: 'guides.tutorialCard',
    area: 'guides',
    tier: 'control',
    label: 'Tutorial card',
    help: 'A single tutorial with its title and estimated time. Pick one to start an interactive walkthrough that teaches the workflow by having you do it.',
    importance: 'secondary',
    requiredForV1: true,
  },
  {
    key: 'guides.start',
    area: 'guides',
    tier: 'control',
    label: 'Start tutorial button',
    help: 'Launches the selected walkthrough and switches into tutorial mode. From here the app spotlights each step so you learn the task hands-on.',
    importance: 'secondary',
    requiredForV1: true,
  },
  {
    key: 'guides.modeExplanation',
    area: 'guides',
    tier: 'section',
    label: 'Mode explanation',
    help: 'A short primer on demo versus tutorial mode. It sets expectations so a first-time user understands they can explore freely and nothing they do is permanent.',
    importance: 'secondary',
    requiredForV1: false,
  },
  {
    key: 'guides.onboardingChecklist',
    area: 'guides',
    tier: 'section',
    label: 'Onboarding checklist',
    help: 'The same getting-started checklist surfaced inside guides. Completing it walks a new account through its first meaningful actions in order.',
    importance: 'secondary',
    requiredForV1: false,
  },
  {
    key: 'guides.preview',
    area: 'guides',
    tier: 'control',
    label: 'Tutorial preview',
    help: 'A glimpse of what a tutorial covers before you commit. Previewing helps you pick the right walkthrough rather than starting one that is not what you need.',
    importance: 'secondary',
    requiredForV1: false,
  },
];

// ─── Derived lookups & helpers ───────────────────────────────────────────────

/** All entries keyed by their canonical key. O(1) lookup for the help popover. */
export const helpByKey: Readonly<Record<string, HelpEntry>> = Object.fromEntries(
  HELP_CONTENT.map((e) => [e.key, e]),
);

/** Entries grouped by area, in catalog order. */
export const helpByArea = HELP_CONTENT.reduce(
  (acc, entry) => {
    (acc[entry.area] ??= []).push(entry);
    return acc;
  },
  {} as Record<HelpArea, HelpEntry[]>,
);

/** Keys that make up the V1 explainability coverage target. */
export const REQUIRED_V1_HELP_KEYS: readonly string[] = HELP_CONTENT.filter(
  (e) => e.requiredForV1,
).map((e) => e.key);

/** Look up a single help entry by key. */
export function getHelp(key: string | null | undefined): HelpEntry | undefined {
  if (!key) return undefined;
  return helpByKey[key];
}

/** Type guard — true when the string is a catalogued help key. */
export function isHelpKey(key: string): boolean {
  return Object.prototype.hasOwnProperty.call(helpByKey, key);
}
