/**
 * Tutorial Selector Registry
 *
 * Single source of truth for all `data-tour` attribute keys used across
 * the Kleegr mock GHL platform.
 *
 * Rules:
 * - Keys follow the pattern `area.element` (lowercase area, camelCase element).
 * - Module agents add `data-tour={key}` to their JSX using the exact key
 *   strings exported here. They do NOT edit this file unless assigned.
 * - The Tutorial engine uses these keys to locate DOM elements; never
 *   use nth-child, class names, or generated IDs as tutorial targets.
 *
 * This file must have zero external dependencies.
 */

// ─── Types ──────────────────────────────────────────────────────────────────

export type TourArea =
  | 'topbar'
  | 'sidebar'
  | 'dashboard'
  | 'contacts'
  | 'conversations'
  | 'opportunities'
  | 'calendars'
  | 'tasks'
  | 'automations'
  | 'marketing'
  | 'reputation'
  | 'phone'
  | 'payments'
  | 'integrations'
  | 'guides'
  | 'settings'
  | 'reporting'
  | 'sites';

/**
 * Every known `data-tour` key in the app.
 * Using a union type keeps assignments typo-proof when the engine consumes them.
 */
export type TourKey =
  // ── TopBar ──
  | 'topbar'
  | 'topbar.accountSwitcher'
  | 'topbar.search'
  | 'topbar.notifications'
  | 'topbar.quickAdd'
  | 'topbar.modeToggle'
  | 'topbar.resetDemo'
  | 'topbar.guides'
  | 'topbar.userMenu'
  | 'topbar.mobileNav'
  // ── Sidebar ──
  | 'sidebar'
  | 'sidebar.logo'
  | 'sidebar.collapseToggle'
  | 'nav.dashboard'
  | 'nav.conversations'
  | 'nav.contacts'
  | 'nav.opportunities'
  | 'nav.calendars'
  | 'nav.marketing'
  | 'nav.automations'
  | 'nav.sites'
  | 'nav.reputation'
  | 'nav.reporting'
  | 'nav.payments'
  | 'nav.phone'
  | 'nav.tasks'
  | 'nav.integrations'
  | 'nav.media'
  | 'nav.settings'
  | 'nav.guides'
  // ── Dashboard ──
  | 'dashboard.page'
  | 'dashboard.kpis'
  | 'dashboard.kpi.pipelineValue'
  | 'dashboard.kpi.openOpps'
  | 'dashboard.kpi.newContacts'
  | 'dashboard.kpi.unreadConvs'
  | 'dashboard.kpi.upcomingAppts'
  | 'dashboard.kpi.revenue'
  | 'dashboard.kpi.tasksDue'
  | 'dashboard.kpi.reviews'
  | 'dashboard.pipelineChart'
  | 'dashboard.leadSources'
  | 'dashboard.revenueChart'
  | 'dashboard.leadTrend'
  | 'dashboard.activity'
  | 'dashboard.tasksDue'
  | 'dashboard.appointments'
  | 'dashboard.onboardingChecklist'
  // ── Contacts ──
  | 'contacts.page'
  | 'contacts.addButton'
  | 'contacts.search'
  | 'contacts.smartLists'
  | 'contacts.filters'
  | 'contacts.table'
  | 'contacts.row'
  | 'contacts.detail'
  | 'contacts.detailTabs'
  | 'contacts.addModal'
  | 'contacts.addSubmit'
  // ── Conversations ──
  | 'conversations.page'
  | 'conversations.inbox'
  | 'conversations.filters'
  | 'conversations.list'
  | 'conversations.threadItem'
  | 'conversations.thread'
  | 'conversations.composer'
  | 'conversations.sendButton'
  | 'conversations.contactContext'
  // ── Opportunities ──
  | 'opportunities.page'
  | 'opportunities.pipelineSelector'
  | 'opportunities.viewToggle'
  | 'opportunities.board'
  | 'opportunities.stageColumn'
  | 'opportunities.card'
  | 'opportunities.moveCard'
  | 'opportunities.detail'
  | 'opportunities.list'
  // ── Calendars ──
  | 'calendars.page'
  | 'calendars.bookButton'
  | 'calendars.selector'
  | 'calendars.viewToggle'
  | 'calendars.monthGrid'
  | 'calendars.weekView'
  | 'calendars.agenda'
  | 'calendars.appointmentChip'
  | 'calendars.appointmentDetail'
  | 'calendars.bookModal'
  | 'calendars.bookSubmit'
  // ── Tasks ──
  | 'tasks.page'
  | 'tasks.addButton'
  | 'tasks.summary'
  | 'tasks.filters'
  | 'tasks.list'
  | 'tasks.groupedList'
  | 'tasks.row'
  | 'tasks.toggle'
  | 'tasks.detail'
  | 'tasks.addModal'
  | 'tasks.addSubmit'
  // ── Automations ──
  | 'automations.page'
  | 'automations.list'
  | 'automations.row'
  | 'automations.addButton'
  | 'automations.canvas'
  | 'automations.triggerNode'
  | 'automations.actionNode'
  | 'automations.addNodeButton'
  | 'automations.nodeDrawer'
  | 'automations.publishToggle'
  // ── Marketing ──
  | 'marketing.emailPage'
  | 'marketing.emailList'
  | 'marketing.emailRow'
  | 'marketing.emailDetail'
  | 'marketing.emailMetrics'
  | 'marketing.smsPage'
  | 'marketing.smsList'
  | 'marketing.smsRow'
  | 'marketing.smsDetail'
  | 'marketing.smsMetrics'
  // ── Reputation ──
  | 'reputation.page'
  | 'reputation.overview'
  | 'reputation.reviewsList'
  | 'reputation.reviewRow'
  | 'reputation.sendRequestButton'
  | 'reputation.requestModal'
  | 'reputation.requestContactPicker'
  | 'reputation.requestChannelToggle'
  | 'reputation.requestSubmit'
  | 'reputation.replyModal'
  // ── Phone ──
  | 'phone.page'
  | 'phone.callLog'
  | 'phone.callRow'
  | 'phone.missedCallFilter'
  | 'phone.dialerButton'
  | 'phone.dialer'
  | 'phone.dialerInput'
  | 'phone.dialerCall'
  | 'phone.voicemailList'
  | 'phone.voicemailRow'
  | 'phone.callDetail'
  | 'phone.recordingPlayer'
  // ── Payments ──
  | 'payments.page'
  | 'payments.invoiceList'
  | 'payments.invoiceRow'
  | 'payments.createButton'
  | 'payments.invoiceModal'
  | 'payments.invoiceClientPicker'
  | 'payments.invoiceLineItems'
  | 'payments.invoiceAddLine'
  | 'payments.invoiceTotals'
  | 'payments.invoiceSend'
  | 'payments.invoiceDetail'
  | 'payments.transactionList'
  // ── Integrations / Outlook ──
  | 'integrations.page'
  | 'integrations.outlookCard'
  | 'integrations.connectButton'
  | 'integrations.connectModal'
  | 'integrations.connectConfirm'
  | 'integrations.outlookInbox'
  | 'integrations.outlookFolders'
  | 'integrations.outlookList'
  | 'integrations.outlookThread'
  // ── Guides ──
  | 'guides.page'
  | 'guides.launcher'
  | 'guides.list'
  | 'guides.card'
  | 'guides.startButton'
  | 'guides.progressBar'
  | 'guides.completionCard'
  // ── Settings ──
  | 'settings.page'
  | 'settings.nav'
  | 'settings.businessProfile'
  | 'settings.staff'
  | 'settings.addUser'
  // ── Reporting ──
  | 'reporting.page'
  | 'reporting.tabs'
  | 'reporting.dateRange'
  | 'reporting.charts'
  | 'reporting.table'
  | 'reporting.export'
  // ── Sites / Forms / Surveys ──
  | 'sites.page'
  | 'sites.funnelList'
  | 'sites.formList'
  | 'sites.surveyList';

export interface TourRegistryItem {
  /** Exact string used in `data-tour` attributes. */
  key: TourKey;
  area: TourArea;
  /** Human-readable label for documentation and authoring tools. */
  label: string;
  /** Short description of the element this key targets. */
  description: string;
  /** Whether this key must be placed before Wave 1 ships. */
  requiredForV1: boolean;
  /** IDs of the V1 tutorials that require this element to be reachable. */
  tutorials: RequiredTutorialId[];
}

// ─── Required V1 tutorial IDs ─────────────────────────────────────────────

export const REQUIRED_TUTORIAL_IDS = [
  'add-contact',
  'reply-to-conversation',
  'move-pipeline-lead',
  'book-appointment',
  'create-workflow',
  'view-campaign-performance',
  'send-review-request',
  'check-missed-calls',
  'create-invoice',
  'view-outlook-inbox',
] as const;

export type RequiredTutorialId = (typeof REQUIRED_TUTORIAL_IDS)[number];

// ─── Registry ─────────────────────────────────────────────────────────────

export const TOUR_REGISTRY: TourRegistryItem[] = [
  // ── TopBar ──────────────────────────────────────────────────────────────
  {
    key: 'topbar',
    area: 'topbar',
    label: 'Top bar',
    description: 'The entire top navigation bar.',
    requiredForV1: true,
    tutorials: [],
  },
  {
    key: 'topbar.accountSwitcher',
    area: 'topbar',
    label: 'Account switcher',
    description: 'Button that opens the cosmetic demo-account switcher dropdown.',
    requiredForV1: true,
    tutorials: [],
  },
  {
    key: 'topbar.search',
    area: 'topbar',
    label: 'Global search',
    description: 'Search button that opens the command-palette style search overlay.',
    requiredForV1: true,
    tutorials: [],
  },
  {
    key: 'topbar.notifications',
    area: 'topbar',
    label: 'Notification bell',
    description: 'Bell icon that opens the notification center dropdown.',
    requiredForV1: true,
    tutorials: [],
  },
  {
    key: 'topbar.quickAdd',
    area: 'topbar',
    label: 'Quick-add menu',
    description: '+  button that opens the quick-add dropdown for contacts, tasks, etc.',
    requiredForV1: false,
    tutorials: [],
  },
  {
    key: 'topbar.modeToggle',
    area: 'topbar',
    label: 'Mode toggle',
    description: 'Demo / Tutorial mode toggle pill in the top bar.',
    requiredForV1: true,
    tutorials: [],
  },
  {
    key: 'topbar.resetDemo',
    area: 'topbar',
    label: 'Reset Demo button',
    description: 'Button that resets all in-memory state to the seeded defaults.',
    requiredForV1: true,
    tutorials: [],
  },
  {
    key: 'topbar.guides',
    area: 'topbar',
    label: 'Guides launcher',
    description: 'Book/graduation icon that navigates to /guides.',
    requiredForV1: true,
    tutorials: [],
  },
  {
    key: 'topbar.userMenu',
    area: 'topbar',
    label: 'User avatar / menu',
    description: 'Avatar button that opens the user dropdown menu.',
    requiredForV1: true,
    tutorials: [],
  },
  {
    key: 'topbar.mobileNav',
    area: 'topbar',
    label: 'Mobile nav hamburger',
    description: 'Hamburger button visible on mobile that opens the slide-over sidebar.',
    requiredForV1: true,
    tutorials: [],
  },

  // ── Dashboard ────────────────────────────────────────────────────────────
  {
    key: 'dashboard.page',
    area: 'dashboard',
    label: 'Dashboard page',
    description: 'Root element of the Dashboard route.',
    requiredForV1: true,
    tutorials: [],
  },
  {
    key: 'dashboard.kpis',
    area: 'dashboard',
    label: 'KPI stat cards section',
    description: 'The grid of 8 KPI stat cards at the top of the dashboard.',
    requiredForV1: true,
    tutorials: [],
  },
  {
    key: 'dashboard.kpi.pipelineValue',
    area: 'dashboard',
    label: 'Pipeline value KPI card',
    description: 'Stat card showing total open pipeline value.',
    requiredForV1: true,
    tutorials: [],
  },
  {
    key: 'dashboard.kpi.openOpps',
    area: 'dashboard',
    label: 'Open opportunities KPI card',
    description: 'Stat card showing count of open opportunities.',
    requiredForV1: false,
    tutorials: [],
  },
  {
    key: 'dashboard.kpi.newContacts',
    area: 'dashboard',
    label: 'New contacts KPI card',
    description: 'Stat card showing contacts added in the last 30 days.',
    requiredForV1: false,
    tutorials: [],
  },
  {
    key: 'dashboard.kpi.unreadConvs',
    area: 'dashboard',
    label: 'Unread conversations KPI card',
    description: 'Stat card showing unread conversation count.',
    requiredForV1: false,
    tutorials: [],
  },
  {
    key: 'dashboard.kpi.upcomingAppts',
    area: 'dashboard',
    label: 'Upcoming appointments KPI card',
    description: 'Stat card showing upcoming confirmed appointment count.',
    requiredForV1: false,
    tutorials: [],
  },
  {
    key: 'dashboard.kpi.revenue',
    area: 'dashboard',
    label: 'Revenue collected KPI card',
    description: 'Stat card showing total paid invoice revenue.',
    requiredForV1: false,
    tutorials: [],
  },
  {
    key: 'dashboard.kpi.tasksDue',
    area: 'dashboard',
    label: 'Open tasks KPI card',
    description: 'Stat card showing open (and overdue) task count.',
    requiredForV1: false,
    tutorials: [],
  },
  {
    key: 'dashboard.kpi.reviews',
    area: 'dashboard',
    label: 'Average review rating KPI card',
    description: 'Stat card showing average review rating and missed call count.',
    requiredForV1: false,
    tutorials: [],
  },
  {
    key: 'dashboard.pipelineChart',
    area: 'dashboard',
    label: 'Pipeline by stage chart',
    description: 'Bar chart of open deal value per pipeline stage.',
    requiredForV1: true,
    tutorials: [],
  },
  {
    key: 'dashboard.leadSources',
    area: 'dashboard',
    label: 'Lead sources donut chart',
    description: 'Pie/donut chart showing contact breakdown by acquisition channel.',
    requiredForV1: true,
    tutorials: [],
  },
  {
    key: 'dashboard.revenueChart',
    area: 'dashboard',
    label: 'Revenue by month chart',
    description: 'Bar chart of paid invoice revenue by month.',
    requiredForV1: false,
    tutorials: [],
  },
  {
    key: 'dashboard.leadTrend',
    area: 'dashboard',
    label: 'Lead volume trend chart',
    description: 'Line chart of new contact volume over the last 8 days.',
    requiredForV1: false,
    tutorials: [],
  },
  {
    key: 'dashboard.activity',
    area: 'dashboard',
    label: 'Recent activity feed',
    description: 'Chronological list of recent events across all modules.',
    requiredForV1: true,
    tutorials: [],
  },
  {
    key: 'dashboard.tasksDue',
    area: 'dashboard',
    label: 'Tasks due card',
    description: 'Card listing open tasks sorted by due date.',
    requiredForV1: true,
    tutorials: [],
  },
  {
    key: 'dashboard.appointments',
    area: 'dashboard',
    label: 'Upcoming appointments card',
    description: 'Card listing next confirmed appointments.',
    requiredForV1: true,
    tutorials: [],
  },
  {
    key: 'dashboard.onboardingChecklist',
    area: 'dashboard',
    label: 'Onboarding checklist card',
    description: 'Getting-started checklist with progress bar linking to tutorials.',
    requiredForV1: true,
    tutorials: [
      'add-contact',
      'reply-to-conversation',
      'move-pipeline-lead',
      'book-appointment',
      'create-invoice',
    ],
  },

  // ── Contacts ─────────────────────────────────────────────────────────────
  {
    key: 'contacts.page',
    area: 'contacts',
    label: 'Contacts page',
    description: 'Root element of the Contacts/CRM route.',
    requiredForV1: true,
    tutorials: ['add-contact'],
  },
  {
    key: 'contacts.addButton',
    area: 'contacts',
    label: 'Add contact button',
    description: 'Primary CTA button that opens the Add Contact modal.',
    requiredForV1: true,
    tutorials: ['add-contact'],
  },
  {
    key: 'contacts.search',
    area: 'contacts',
    label: 'Contact search input',
    description: 'Search/filter input within the contacts table.',
    requiredForV1: true,
    tutorials: ['add-contact'],
  },
  {
    key: 'contacts.smartLists',
    area: 'contacts',
    label: 'Smart Lists tabs',
    description: 'Saved Smart List tabs above the contacts table.',
    requiredForV1: true,
    tutorials: ['add-contact'],
  },
  {
    key: 'contacts.filters',
    area: 'contacts',
    label: 'Contacts filter bar',
    description: 'Filter controls (tags, source, owner, etc.) for the contacts table.',
    requiredForV1: true,
    tutorials: ['add-contact'],
  },
  {
    key: 'contacts.table',
    area: 'contacts',
    label: 'Contacts table',
    description: 'The main sortable/filterable data table of contacts.',
    requiredForV1: true,
    tutorials: ['add-contact'],
  },
  {
    key: 'contacts.row',
    area: 'contacts',
    label: 'Contact table row',
    description: 'A single row in the contacts table (applied to each <tr>).',
    requiredForV1: true,
    tutorials: ['add-contact'],
  },
  {
    key: 'contacts.detail',
    area: 'contacts',
    label: 'Contact detail page/drawer',
    description: 'The contact detail view (full page or slide-over drawer).',
    requiredForV1: true,
    tutorials: ['add-contact'],
  },
  {
    key: 'contacts.detailTabs',
    area: 'contacts',
    label: 'Contact detail tabs',
    description: 'Tab bar within the contact detail (Activity, Conversations, Tasks, etc.).',
    requiredForV1: true,
    tutorials: ['add-contact'],
  },
  {
    key: 'contacts.addModal',
    area: 'contacts',
    label: 'Add Contact modal',
    description: 'The modal dialog for creating a new contact.',
    requiredForV1: true,
    tutorials: ['add-contact'],
  },
  {
    key: 'contacts.addSubmit',
    area: 'contacts',
    label: 'Add Contact submit button',
    description: 'The primary submit/save button inside the Add Contact modal.',
    requiredForV1: true,
    tutorials: ['add-contact'],
  },

  // ── Conversations ─────────────────────────────────────────────────────────
  {
    key: 'conversations.page',
    area: 'conversations',
    label: 'Conversations page',
    description: 'Root element of the Conversations/Inbox route.',
    requiredForV1: true,
    tutorials: ['reply-to-conversation'],
  },
  {
    key: 'conversations.inbox',
    area: 'conversations',
    label: 'Inbox container',
    description: 'The three-pane inbox layout container.',
    requiredForV1: true,
    tutorials: ['reply-to-conversation'],
  },
  {
    key: 'conversations.filters',
    area: 'conversations',
    label: 'Channel/filter tabs',
    description: 'Channel tabs (All, SMS, Email, etc.) and filter controls.',
    requiredForV1: true,
    tutorials: ['reply-to-conversation'],
  },
  {
    key: 'conversations.list',
    area: 'conversations',
    label: 'Conversation list pane',
    description: 'Left-pane list of conversation thread previews.',
    requiredForV1: true,
    tutorials: ['reply-to-conversation'],
  },
  {
    key: 'conversations.threadItem',
    area: 'conversations',
    label: 'Thread list item',
    description: 'A single conversation preview item in the list pane.',
    requiredForV1: true,
    tutorials: ['reply-to-conversation'],
  },
  {
    key: 'conversations.thread',
    area: 'conversations',
    label: 'Open thread / message view',
    description: 'Center pane showing the full message thread.',
    requiredForV1: true,
    tutorials: ['reply-to-conversation'],
  },
  {
    key: 'conversations.composer',
    area: 'conversations',
    label: 'Message composer',
    description: 'The reply text input / composer at the bottom of the thread pane.',
    requiredForV1: true,
    tutorials: ['reply-to-conversation'],
  },
  {
    key: 'conversations.sendButton',
    area: 'conversations',
    label: 'Send message button',
    description: 'The send / submit button in the message composer.',
    requiredForV1: true,
    tutorials: ['reply-to-conversation'],
  },
  {
    key: 'conversations.contactContext',
    area: 'conversations',
    label: 'Contact context pane',
    description: 'Right-pane contact information panel in the inbox.',
    requiredForV1: true,
    tutorials: ['reply-to-conversation'],
  },

  // ── Opportunities ─────────────────────────────────────────────────────────
  {
    key: 'opportunities.page',
    area: 'opportunities',
    label: 'Opportunities / Pipelines page',
    description: 'Root element of the Opportunities route.',
    requiredForV1: true,
    tutorials: ['move-pipeline-lead'],
  },
  {
    key: 'opportunities.pipelineSelector',
    area: 'opportunities',
    label: 'Pipeline selector dropdown',
    description: 'Dropdown to switch between available pipelines.',
    requiredForV1: true,
    tutorials: ['move-pipeline-lead'],
  },
  {
    key: 'opportunities.viewToggle',
    area: 'opportunities',
    label: 'Board / List view toggle',
    description: 'Toggle between Kanban board and list view.',
    requiredForV1: true,
    tutorials: ['move-pipeline-lead'],
  },
  {
    key: 'opportunities.board',
    area: 'opportunities',
    label: 'Kanban pipeline board',
    description: 'The full Kanban board container with stage columns.',
    requiredForV1: true,
    tutorials: ['move-pipeline-lead'],
  },
  {
    key: 'opportunities.stageColumn',
    area: 'opportunities',
    label: 'Pipeline stage column',
    description: 'A single stage column on the Kanban board (applied per column).',
    requiredForV1: true,
    tutorials: ['move-pipeline-lead'],
  },
  {
    key: 'opportunities.card',
    area: 'opportunities',
    label: 'Opportunity card',
    description: 'A draggable deal card on the Kanban board.',
    requiredForV1: true,
    tutorials: ['move-pipeline-lead'],
  },
  {
    key: 'opportunities.moveCard',
    area: 'opportunities',
    label: 'Move card drag handle / target',
    description: 'The drag handle on an opportunity card or the drop-zone used in simulated tutorials.',
    requiredForV1: true,
    tutorials: ['move-pipeline-lead'],
  },
  {
    key: 'opportunities.detail',
    area: 'opportunities',
    label: 'Opportunity detail panel',
    description: 'The opportunity detail modal or drawer.',
    requiredForV1: true,
    tutorials: ['move-pipeline-lead'],
  },
  {
    key: 'opportunities.list',
    area: 'opportunities',
    label: 'Opportunities list view',
    description: 'The list/table view of all opportunities.',
    requiredForV1: false,
    tutorials: [],
  },

  // ── Calendars ─────────────────────────────────────────────────────────────
  {
    key: 'calendars.page',
    area: 'calendars',
    label: 'Calendars page',
    description: 'Root element of the Calendars route.',
    requiredForV1: true,
    tutorials: ['book-appointment'],
  },
  {
    key: 'calendars.bookButton',
    area: 'calendars',
    label: 'Book appointment button',
    description: 'Primary CTA button that opens the appointment booking modal.',
    requiredForV1: true,
    tutorials: ['book-appointment'],
  },
  {
    key: 'calendars.selector',
    area: 'calendars',
    label: 'Calendar selector',
    description: 'Dropdown or list to filter by a specific calendar.',
    requiredForV1: true,
    tutorials: ['book-appointment'],
  },
  {
    key: 'calendars.viewToggle',
    area: 'calendars',
    label: 'View toggle (month/week/day/agenda)',
    description: 'Tab-style toggle to switch calendar view modes.',
    requiredForV1: true,
    tutorials: ['book-appointment'],
  },
  {
    key: 'calendars.monthGrid',
    area: 'calendars',
    label: 'Month grid view',
    description: 'The full month calendar grid.',
    requiredForV1: true,
    tutorials: ['book-appointment'],
  },
  {
    key: 'calendars.weekView',
    area: 'calendars',
    label: 'Week/day time-grid view',
    description: 'The time-grid view for week or day.',
    requiredForV1: false,
    tutorials: [],
  },
  {
    key: 'calendars.agenda',
    area: 'calendars',
    label: 'Agenda list view',
    description: 'List-style agenda view of appointments.',
    requiredForV1: false,
    tutorials: [],
  },
  {
    key: 'calendars.appointmentChip',
    area: 'calendars',
    label: 'Appointment chip / event chip',
    description: 'A clickable appointment event chip on the calendar grid.',
    requiredForV1: true,
    tutorials: ['book-appointment'],
  },
  {
    key: 'calendars.appointmentDetail',
    area: 'calendars',
    label: 'Appointment detail panel',
    description: 'The appointment detail modal or drawer.',
    requiredForV1: true,
    tutorials: ['book-appointment'],
  },
  {
    key: 'calendars.bookModal',
    area: 'calendars',
    label: 'Book appointment modal',
    description: 'The modal dialog for creating or editing an appointment.',
    requiredForV1: true,
    tutorials: ['book-appointment'],
  },
  {
    key: 'calendars.bookSubmit',
    area: 'calendars',
    label: 'Book appointment submit button',
    description: 'The confirm/save button inside the booking modal.',
    requiredForV1: true,
    tutorials: ['book-appointment'],
  },

  // ── Tasks ─────────────────────────────────────────────────────────────────
  {
    key: 'tasks.page',
    area: 'tasks',
    label: 'Tasks page',
    description: 'Root element of the Tasks route.',
    requiredForV1: true,
    tutorials: [],
  },
  {
    key: 'tasks.addButton',
    area: 'tasks',
    label: 'Add task button',
    description: 'Primary CTA button that opens the Add Task modal.',
    requiredForV1: true,
    tutorials: [],
  },
  {
    key: 'tasks.summary',
    area: 'tasks',
    label: 'Tasks summary bar',
    description: 'Summary counts (open, overdue, due today) at the top of the tasks page.',
    requiredForV1: false,
    tutorials: [],
  },
  {
    key: 'tasks.filters',
    area: 'tasks',
    label: 'Tasks filter bar',
    description: 'Filter controls (due today, overdue, mine, priority).',
    requiredForV1: true,
    tutorials: [],
  },
  {
    key: 'tasks.list',
    area: 'tasks',
    label: 'Tasks list',
    description: 'The main flat list of tasks.',
    requiredForV1: true,
    tutorials: [],
  },
  {
    key: 'tasks.groupedList',
    area: 'tasks',
    label: 'Tasks grouped list',
    description: 'Tasks list grouped by due date sections.',
    requiredForV1: false,
    tutorials: [],
  },
  {
    key: 'tasks.row',
    area: 'tasks',
    label: 'Task row',
    description: 'A single task row in the tasks list.',
    requiredForV1: true,
    tutorials: [],
  },
  {
    key: 'tasks.toggle',
    area: 'tasks',
    label: 'Task complete toggle',
    description: 'Checkbox/toggle to mark a task complete or incomplete.',
    requiredForV1: true,
    tutorials: [],
  },
  {
    key: 'tasks.detail',
    area: 'tasks',
    label: 'Task detail panel',
    description: 'The task detail modal or inline expansion.',
    requiredForV1: false,
    tutorials: [],
  },
  {
    key: 'tasks.addModal',
    area: 'tasks',
    label: 'Add Task modal',
    description: 'The modal dialog for creating a new task.',
    requiredForV1: true,
    tutorials: [],
  },
  {
    key: 'tasks.addSubmit',
    area: 'tasks',
    label: 'Add Task submit button',
    description: 'The primary submit button inside the Add Task modal.',
    requiredForV1: true,
    tutorials: [],
  },

  // ── Automations ───────────────────────────────────────────────────────────
  {
    key: 'automations.page',
    area: 'automations',
    label: 'Automations / Workflows page',
    description: 'Root element of the Automations route.',
    requiredForV1: true,
    tutorials: ['create-workflow'],
  },
  {
    key: 'automations.list',
    area: 'automations',
    label: 'Workflow list',
    description: 'Table/list of all workflows.',
    requiredForV1: true,
    tutorials: ['create-workflow'],
  },
  {
    key: 'automations.row',
    area: 'automations',
    label: 'Workflow list row',
    description: 'A single row in the workflow list.',
    requiredForV1: true,
    tutorials: ['create-workflow'],
  },
  {
    key: 'automations.addButton',
    area: 'automations',
    label: 'Create workflow button',
    description: 'Button to create a new workflow.',
    requiredForV1: true,
    tutorials: ['create-workflow'],
  },
  {
    key: 'automations.canvas',
    area: 'automations',
    label: 'Workflow builder canvas',
    description: 'The flow canvas area where trigger and action nodes are displayed.',
    requiredForV1: true,
    tutorials: ['create-workflow'],
  },
  {
    key: 'automations.triggerNode',
    area: 'automations',
    label: 'Trigger node',
    description: 'The trigger node at the top of the workflow canvas.',
    requiredForV1: true,
    tutorials: ['create-workflow'],
  },
  {
    key: 'automations.actionNode',
    area: 'automations',
    label: 'Action node',
    description: 'An action node on the workflow canvas.',
    requiredForV1: true,
    tutorials: ['create-workflow'],
  },
  {
    key: 'automations.addNodeButton',
    area: 'automations',
    label: 'Add node button',
    description: 'Button or + icon to add a new action node to the canvas.',
    requiredForV1: true,
    tutorials: ['create-workflow'],
  },
  {
    key: 'automations.nodeDrawer',
    area: 'automations',
    label: 'Node settings drawer',
    description: 'The right-side drawer that opens when a node is clicked to configure it.',
    requiredForV1: true,
    tutorials: ['create-workflow'],
  },
  {
    key: 'automations.publishToggle',
    area: 'automations',
    label: 'Publish / draft toggle',
    description: 'Toggle to switch a workflow between Published and Draft status.',
    requiredForV1: true,
    tutorials: ['create-workflow'],
  },

  // ── Marketing ─────────────────────────────────────────────────────────────
  {
    key: 'marketing.emailPage',
    area: 'marketing',
    label: 'Email campaigns page',
    description: 'Root element of the Email Campaigns route.',
    requiredForV1: true,
    tutorials: ['view-campaign-performance'],
  },
  {
    key: 'marketing.emailList',
    area: 'marketing',
    label: 'Email campaigns list',
    description: 'Table/list of all email campaigns.',
    requiredForV1: true,
    tutorials: ['view-campaign-performance'],
  },
  {
    key: 'marketing.emailRow',
    area: 'marketing',
    label: 'Email campaign row',
    description: 'A single row in the email campaign list.',
    requiredForV1: true,
    tutorials: ['view-campaign-performance'],
  },
  {
    key: 'marketing.emailDetail',
    area: 'marketing',
    label: 'Email campaign detail page',
    description: 'The detail/analytics page for a single email campaign.',
    requiredForV1: true,
    tutorials: ['view-campaign-performance'],
  },
  {
    key: 'marketing.emailMetrics',
    area: 'marketing',
    label: 'Email campaign metrics section',
    description: 'The open rate, click rate, bounce rate, and delivery metrics within the campaign detail.',
    requiredForV1: true,
    tutorials: ['view-campaign-performance'],
  },
  {
    key: 'marketing.smsPage',
    area: 'marketing',
    label: 'SMS campaigns page',
    description: 'Root element of the SMS Campaigns route.',
    requiredForV1: false,
    tutorials: [],
  },
  {
    key: 'marketing.smsList',
    area: 'marketing',
    label: 'SMS campaigns list',
    description: 'Table/list of all SMS campaigns.',
    requiredForV1: false,
    tutorials: [],
  },
  {
    key: 'marketing.smsRow',
    area: 'marketing',
    label: 'SMS campaign row',
    description: 'A single row in the SMS campaign list.',
    requiredForV1: false,
    tutorials: [],
  },
  {
    key: 'marketing.smsDetail',
    area: 'marketing',
    label: 'SMS campaign detail page',
    description: 'The detail/analytics page for a single SMS campaign.',
    requiredForV1: false,
    tutorials: [],
  },
  {
    key: 'marketing.smsMetrics',
    area: 'marketing',
    label: 'SMS campaign metrics section',
    description: 'Delivered %, reply %, opt-out % metrics within the SMS campaign detail.',
    requiredForV1: false,
    tutorials: [],
  },

  // ── Reputation ────────────────────────────────────────────────────────────
  {
    key: 'reputation.page',
    area: 'reputation',
    label: 'Reputation page',
    description: 'Root element of the Reputation route.',
    requiredForV1: true,
    tutorials: ['send-review-request'],
  },
  {
    key: 'reputation.overview',
    area: 'reputation',
    label: 'Reputation overview section',
    description: 'Average rating, total reviews, and source breakdown cards.',
    requiredForV1: true,
    tutorials: ['send-review-request'],
  },
  {
    key: 'reputation.reviewsList',
    area: 'reputation',
    label: 'Reviews list',
    description: 'Table/list of all individual reviews.',
    requiredForV1: true,
    tutorials: ['send-review-request'],
  },
  {
    key: 'reputation.reviewRow',
    area: 'reputation',
    label: 'Review row',
    description: 'A single review row in the reviews list.',
    requiredForV1: true,
    tutorials: ['send-review-request'],
  },
  {
    key: 'reputation.sendRequestButton',
    area: 'reputation',
    label: 'Send review request button',
    description: 'Primary CTA that opens the Send Review Request modal.',
    requiredForV1: true,
    tutorials: ['send-review-request'],
  },
  {
    key: 'reputation.requestModal',
    area: 'reputation',
    label: 'Send review request modal',
    description: 'The modal dialog for sending a review request to a contact.',
    requiredForV1: true,
    tutorials: ['send-review-request'],
  },
  {
    key: 'reputation.requestContactPicker',
    area: 'reputation',
    label: 'Request modal — contact picker',
    description: 'Contact selector field inside the review request modal.',
    requiredForV1: true,
    tutorials: ['send-review-request'],
  },
  {
    key: 'reputation.requestChannelToggle',
    area: 'reputation',
    label: 'Request modal — SMS/Email channel toggle',
    description: 'Toggle to choose SMS or Email delivery channel. Used for branching in the tutorial.',
    requiredForV1: true,
    tutorials: ['send-review-request'],
  },
  {
    key: 'reputation.requestSubmit',
    area: 'reputation',
    label: 'Request modal — send/submit button',
    description: 'The confirm/send button inside the review request modal.',
    requiredForV1: true,
    tutorials: ['send-review-request'],
  },
  {
    key: 'reputation.replyModal',
    area: 'reputation',
    label: 'Reply to review modal',
    description: 'Modal for composing a reply to an existing review.',
    requiredForV1: false,
    tutorials: [],
  },

  // ── Phone ─────────────────────────────────────────────────────────────────
  {
    key: 'phone.page',
    area: 'phone',
    label: 'Phone / Call log page',
    description: 'Root element of the Phone route.',
    requiredForV1: true,
    tutorials: ['check-missed-calls'],
  },
  {
    key: 'phone.callLog',
    area: 'phone',
    label: 'Call log table',
    description: 'The table of all call records (inbound, outbound, missed).',
    requiredForV1: true,
    tutorials: ['check-missed-calls'],
  },
  {
    key: 'phone.callRow',
    area: 'phone',
    label: 'Call log row',
    description: 'A single row in the call log table.',
    requiredForV1: true,
    tutorials: ['check-missed-calls'],
  },
  {
    key: 'phone.missedCallFilter',
    area: 'phone',
    label: 'Missed calls filter',
    description: 'Filter button or tab to show only missed calls.',
    requiredForV1: true,
    tutorials: ['check-missed-calls'],
  },
  {
    key: 'phone.dialerButton',
    area: 'phone',
    label: 'Open dialer button',
    description: 'Button that navigates to or opens the dialer.',
    requiredForV1: false,
    tutorials: [],
  },
  {
    key: 'phone.dialer',
    area: 'phone',
    label: 'Dialer',
    description: 'The number-pad dialer UI.',
    requiredForV1: false,
    tutorials: [],
  },
  {
    key: 'phone.dialerInput',
    area: 'phone',
    label: 'Dialer number input',
    description: 'The phone number display/input in the dialer.',
    requiredForV1: false,
    tutorials: [],
  },
  {
    key: 'phone.dialerCall',
    area: 'phone',
    label: 'Dialer call button',
    description: 'The green call button in the dialer.',
    requiredForV1: false,
    tutorials: [],
  },
  {
    key: 'phone.voicemailList',
    area: 'phone',
    label: 'Voicemail list',
    description: 'List of voicemail entries.',
    requiredForV1: false,
    tutorials: [],
  },
  {
    key: 'phone.voicemailRow',
    area: 'phone',
    label: 'Voicemail row',
    description: 'A single voicemail entry in the voicemail list.',
    requiredForV1: false,
    tutorials: [],
  },
  {
    key: 'phone.callDetail',
    area: 'phone',
    label: 'Call detail page',
    description: 'The detail view for a single call record.',
    requiredForV1: true,
    tutorials: ['check-missed-calls'],
  },
  {
    key: 'phone.recordingPlayer',
    area: 'phone',
    label: 'Recording player',
    description: 'Cosmetic audio player UI for the fake call recording.',
    requiredForV1: false,
    tutorials: [],
  },

  // ── Payments ──────────────────────────────────────────────────────────────
  {
    key: 'payments.page',
    area: 'payments',
    label: 'Payments page',
    description: 'Root element of the Payments route.',
    requiredForV1: true,
    tutorials: ['create-invoice'],
  },
  {
    key: 'payments.invoiceList',
    area: 'payments',
    label: 'Invoices list',
    description: 'Table of all invoices.',
    requiredForV1: true,
    tutorials: ['create-invoice'],
  },
  {
    key: 'payments.invoiceRow',
    area: 'payments',
    label: 'Invoice row',
    description: 'A single row in the invoice table.',
    requiredForV1: true,
    tutorials: ['create-invoice'],
  },
  {
    key: 'payments.createButton',
    area: 'payments',
    label: 'Create invoice button',
    description: 'Primary CTA button that opens the new invoice modal or builder.',
    requiredForV1: true,
    tutorials: ['create-invoice'],
  },
  {
    key: 'payments.invoiceModal',
    area: 'payments',
    label: 'Create invoice modal / builder',
    description: 'The modal or full-page invoice builder.',
    requiredForV1: true,
    tutorials: ['create-invoice'],
  },
  {
    key: 'payments.invoiceClientPicker',
    area: 'payments',
    label: 'Invoice client picker',
    description: 'Contact selector field in the invoice builder.',
    requiredForV1: true,
    tutorials: ['create-invoice'],
  },
  {
    key: 'payments.invoiceLineItems',
    area: 'payments',
    label: 'Invoice line items section',
    description: 'The line-items table within the invoice builder.',
    requiredForV1: true,
    tutorials: ['create-invoice'],
  },
  {
    key: 'payments.invoiceAddLine',
    area: 'payments',
    label: 'Add line item button',
    description: 'Button to add a new line item row to the invoice.',
    requiredForV1: true,
    tutorials: ['create-invoice'],
  },
  {
    key: 'payments.invoiceTotals',
    area: 'payments',
    label: 'Invoice totals section',
    description: 'Subtotal, tax, and total amount section of the invoice builder.',
    requiredForV1: true,
    tutorials: ['create-invoice'],
  },
  {
    key: 'payments.invoiceSend',
    area: 'payments',
    label: 'Send invoice button',
    description: 'The send/confirm button that finalises the invoice (shows success toast).',
    requiredForV1: true,
    tutorials: ['create-invoice'],
  },
  {
    key: 'payments.invoiceDetail',
    area: 'payments',
    label: 'Invoice detail page',
    description: 'The detail view/document preview for a single invoice.',
    requiredForV1: true,
    tutorials: ['create-invoice'],
  },
  {
    key: 'payments.transactionList',
    area: 'payments',
    label: 'Transactions list',
    description: 'Table of all payment transactions.',
    requiredForV1: false,
    tutorials: [],
  },

  // ── Integrations / Outlook ─────────────────────────────────────────────────
  {
    key: 'integrations.page',
    area: 'integrations',
    label: 'Integrations / Connected accounts page',
    description: 'Root element of the Integrations settings route.',
    requiredForV1: true,
    tutorials: ['view-outlook-inbox'],
  },
  {
    key: 'integrations.outlookCard',
    area: 'integrations',
    label: 'Outlook connect card',
    description: 'The integration card for connecting an Outlook account.',
    requiredForV1: true,
    tutorials: ['view-outlook-inbox'],
  },
  {
    key: 'integrations.connectButton',
    area: 'integrations',
    label: 'Connect Outlook button',
    description: 'Button on the Outlook card that triggers the mock OAuth flow.',
    requiredForV1: true,
    tutorials: ['view-outlook-inbox'],
  },
  {
    key: 'integrations.connectModal',
    area: 'integrations',
    label: 'Mock OAuth connect modal',
    description: 'The fake OAuth consent screen modal.',
    requiredForV1: true,
    tutorials: ['view-outlook-inbox'],
  },
  {
    key: 'integrations.connectConfirm',
    area: 'integrations',
    label: 'Connect confirm button',
    description: 'The confirm/allow button inside the mock OAuth modal.',
    requiredForV1: true,
    tutorials: ['view-outlook-inbox'],
  },
  {
    key: 'integrations.outlookInbox',
    area: 'integrations',
    label: 'Outlook-style inbox view',
    description: 'The three-pane Outlook-style inbox shown after connecting.',
    requiredForV1: true,
    tutorials: ['view-outlook-inbox'],
  },
  {
    key: 'integrations.outlookFolders',
    area: 'integrations',
    label: 'Outlook inbox folder list',
    description: 'Folder list pane (Inbox, Sent, Drafts) in the Outlook view.',
    requiredForV1: true,
    tutorials: ['view-outlook-inbox'],
  },
  {
    key: 'integrations.outlookList',
    area: 'integrations',
    label: 'Outlook message list pane',
    description: 'Middle pane listing email message previews.',
    requiredForV1: true,
    tutorials: ['view-outlook-inbox'],
  },
  {
    key: 'integrations.outlookThread',
    area: 'integrations',
    label: 'Outlook reading pane',
    description: 'Right pane showing the selected email message body.',
    requiredForV1: true,
    tutorials: ['view-outlook-inbox'],
  },

  // ── Guides ────────────────────────────────────────────────────────────────
  {
    key: 'guides.page',
    area: 'guides',
    label: 'Guides / Tutorial launcher page',
    description: 'Root element of the /guides route.',
    requiredForV1: true,
    tutorials: [],
  },
  {
    key: 'guides.launcher',
    area: 'guides',
    label: 'Tutorial launcher container',
    description: 'The outer container of the tutorial selection UI.',
    requiredForV1: true,
    tutorials: [],
  },
  {
    key: 'guides.list',
    area: 'guides',
    label: 'Tutorial card list',
    description: 'The grid or list of available tutorial cards.',
    requiredForV1: true,
    tutorials: [],
  },
  {
    key: 'guides.card',
    area: 'guides',
    label: 'Tutorial card',
    description: 'A single tutorial card in the guides list.',
    requiredForV1: true,
    tutorials: [],
  },
  {
    key: 'guides.startButton',
    area: 'guides',
    label: 'Start tutorial button',
    description: 'The start/launch button on each tutorial card.',
    requiredForV1: true,
    tutorials: [],
  },
  {
    key: 'guides.progressBar',
    area: 'guides',
    label: 'Overall tutorials progress bar',
    description: 'Overall progress bar showing how many of the 10 tutorials are complete.',
    requiredForV1: true,
    tutorials: [],
  },
  {
    key: 'guides.completionCard',
    area: 'guides',
    label: 'Tutorial completion card',
    description: 'The celebratory completion screen shown at the end of each tutorial.',
    requiredForV1: true,
    tutorials: [],
  },

  // ── Settings ──────────────────────────────────────────────────────────────
  {
    key: 'settings.page',
    area: 'settings',
    label: 'Settings page',
    description: 'Root element of the Settings hub route.',
    requiredForV1: false,
    tutorials: [],
  },
  {
    key: 'settings.nav',
    area: 'settings',
    label: 'Settings navigation',
    description: 'The settings section navigation list.',
    requiredForV1: false,
    tutorials: [],
  },
  {
    key: 'settings.businessProfile',
    area: 'settings',
    label: 'Business profile form',
    description: 'The editable business profile settings form.',
    requiredForV1: false,
    tutorials: [],
  },
  {
    key: 'settings.staff',
    area: 'settings',
    label: 'Staff / users table',
    description: 'The team/staff management section.',
    requiredForV1: false,
    tutorials: [],
  },
  {
    key: 'settings.addUser',
    area: 'settings',
    label: 'Add user button',
    description: 'Button to open the Add User modal.',
    requiredForV1: false,
    tutorials: [],
  },

  // ── Reporting ─────────────────────────────────────────────────────────────
  {
    key: 'reporting.page',
    area: 'reporting',
    label: 'Reporting page',
    description: 'Root element of the Reporting route.',
    requiredForV1: true,
    tutorials: ['view-campaign-performance'],
  },
  {
    key: 'reporting.tabs',
    area: 'reporting',
    label: 'Report type tabs',
    description: 'Tabs to switch between report types (Attribution, Calls, Appointments, etc.).',
    requiredForV1: true,
    tutorials: ['view-campaign-performance'],
  },
  {
    key: 'reporting.dateRange',
    area: 'reporting',
    label: 'Date range picker',
    description: 'Date range selector for filtering report data.',
    requiredForV1: true,
    tutorials: [],
  },
  {
    key: 'reporting.charts',
    area: 'reporting',
    label: 'Report charts section',
    description: 'The main chart area of any report.',
    requiredForV1: true,
    tutorials: ['view-campaign-performance'],
  },
  {
    key: 'reporting.table',
    area: 'reporting',
    label: 'Report data table',
    description: 'The data table below the charts in any report.',
    requiredForV1: true,
    tutorials: ['view-campaign-performance'],
  },
  {
    key: 'reporting.export',
    area: 'reporting',
    label: 'Export report button',
    description: 'Cosmetic export button (CSV/PDF toast).',
    requiredForV1: false,
    tutorials: [],
  },

  // ── Sites / Forms / Surveys ────────────────────────────────────────────────
  {
    key: 'sites.page',
    area: 'sites',
    label: 'Sites page',
    description: 'Root element of the Sites route (Funnels, Websites, Blogs tabs).',
    requiredForV1: false,
    tutorials: [],
  },
  {
    key: 'sites.funnelList',
    area: 'sites',
    label: 'Funnels list',
    description: 'Card grid of funnels on the Sites page.',
    requiredForV1: false,
    tutorials: [],
  },
  {
    key: 'sites.formList',
    area: 'sites',
    label: 'Forms list',
    description: 'List of forms on the Forms page.',
    requiredForV1: false,
    tutorials: [],
  },
  {
    key: 'sites.surveyList',
    area: 'sites',
    label: 'Surveys list',
    description: 'List of surveys on the Surveys page.',
    requiredForV1: false,
    tutorials: [],
  },
];

// ─── Derived lookups ──────────────────────────────────────────────────────

/** All registry items keyed by their `data-tour` value. O(1) lookup. */
export const tourKeyMap: Readonly<Record<string, TourRegistryItem>> = Object.fromEntries(
  TOUR_REGISTRY.map((item) => [item.key, item]),
);

/** All items grouped by area. */
export const tourKeysByArea: Readonly<Record<TourArea, TourRegistryItem[]>> = (
  TOUR_REGISTRY.reduce(
    (acc, item) => {
      acc[item.area] = acc[item.area] ?? [];
      acc[item.area].push(item);
      return acc;
    },
    {} as Record<TourArea, TourRegistryItem[]>,
  )
) as Readonly<Record<TourArea, TourRegistryItem[]>>;

/** Items that must have their `data-tour` attribute placed before Wave 1 ships. */
export const requiredTourKeys: readonly TourRegistryItem[] = TOUR_REGISTRY.filter(
  (item) => item.requiredForV1,
);

/**
 * Type guard — confirms a string is a known TourKey.
 * Use in the Tutorial engine when consuming step `targetSelector` values.
 */
export function isKnownTourKey(key: string): key is TourKey {
  return Object.prototype.hasOwnProperty.call(tourKeyMap, key);
}
